In [1]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error, root_mean_squared_error

In [2]:
df = pd.read_csv('Student_Performance.csv')

In [3]:
df

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
0,7,99,Yes,9,1,91.0
1,4,82,No,4,2,65.0
2,8,51,Yes,7,2,45.0
3,5,52,Yes,5,2,36.0
4,7,75,No,8,5,66.0
...,...,...,...,...,...,...
9995,1,49,Yes,4,2,23.0
9996,7,64,Yes,8,5,58.0
9997,6,83,Yes,8,5,74.0
9998,9,97,Yes,7,0,95.0
9999,7,74,No,8,1,64.0

In [4]:
df.corr(numeric_only=True)

,Hours Studied,Previous Scores,Sleep Hours,Sample Question Papers Practiced,Performance Index
Hours Studied,1.000000,-0.012390,0.001245,0.017463,0.373730
Previous Scores,-0.012390,1.000000,0.005944,0.007888,0.915189
Sleep Hours,0.001245,0.005944,1.000000,0.003990,0.048106
Sample Question Papers Practiced,0.017463,0.007888,0.003990,1.000000,0.043268
Performance Index,0.373730,0.915189,0.048106,0.043268,1.000000

In [5]:
df.duplicated().sum()

127

In [6]:
df  = df.drop_duplicates()

In [7]:
df.duplicated().sum()

0

In [8]:
df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes' : 1, 'No' : 0})

C:\Users\HP\AppData\Local\Temp\ipykernel_13940\451230903.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Extracurricular Activities'] = df['Extracurricular Activities'].map({'Yes' : 1, 'No' : 0})

In [9]:
df.columns

Index(['Hours Studied', 'Previous Scores', 'Extracurricular Activities',
       'Sleep Hours', 'Sample Question Papers Practiced', 'Performance Index'],
      dtype='object')

In [10]:
# if we have any one column has strong relation with output column then we can use linear regression
df.corr(numeric_only=True)

,Hours Studied,Previous Scores,Extracurricular Activities,Sleep Hours,Sample Question Papers Practiced,Performance Index
Hours Studied,1.000000,-0.010676,0.004899,0.002131,0.015740,0.375332
Previous Scores,-0.010676,1.000000,0.009534,0.007975,0.008719,0.915135
Extracurricular Activities,0.004899,0.009534,1.000000,-0.024008,0.013839,0.026075
Sleep Hours,0.002131,0.007975,-0.024008,1.000000,0.004907,0.050352
Sample Question Papers Practiced,0.015740,0.008719,0.013839,0.004907,1.000000,0.043436
Performance Index,0.375332,0.915135,0.026075,0.050352,0.043436,1.000000

In [11]:
x = df[['Hours Studied', 'Previous Scores', 'Extracurricular Activities', 'Sleep Hours', 'Sample Question Papers Practiced']]
y = df['Performance Index']

In [12]:
# train_test_split() - returns 4 values
xtrain, xtest, ytrain, ytest = train_test_split(x, y, train_size=0.8, random_state=42)

In [13]:
print(xtrain)

      Hours Studied  Previous Scores  Extracurricular Activities  Sleep Hours  \
8591              5               71                           0            4
9120              2               57                           1            7
4112              1               49                           0            4
811               3               58                           1            6
6848              3               80                           0            8
...             ...              ...                         ...          ...
5771              2               46                           0            6
5221              9               60                           1            4
5424              5               95                           1            5
860               1               47                           0            9
7337              9               84                           0            8

      Sample Question Papers Practiced
8591                                 4
9120                                 1
4112                                 0
811                                  1
6848                                 8
...                                ...
5771                                 5
5221                                 3
5424                                 6
860                                  0
7337                                 5

[7898 rows x 5 columns]

In [14]:
# model creation
model = LinearRegression()

In [15]:
# model training
# fit() used for model training it learns the patterns from input and output
model.fit(xtrain, ytrain)

LinearRegression()

In [16]:
model.intercept_

-33.981324496440706

Intercept conclusion

Base or initial value of 'performance index' is -33.981324496440706 when all features equals to zero

In [17]:
model.coef_

array([2.8510219 , 1.01843034, 0.57382297, 0.47207329, 0.18870366])

### Model Evaluation

In [18]:
# Model evaluation on train data
# Error = Actual output - predicted output

# ytrain(actual)
# ytrain_predicted(predicted_values)
'''
syntax 
model.predict(x)
ytrain_predicted = model.predict(xtrain)
ytest_predicted = model.predict(xtest)

'''
ytrain_predicted = model.predict(xtrain)

In [19]:
ytrain_predicted

array([55.22544719, 33.83828856, 20.66107741, ..., 81.09107901,
       20.98458319, 81.94612608])

In [20]:
'''
Syntaxt for metrics

metricname(actual_optput, predicted_output)
r2_score(ytrain, ytrain_predicted)
r2_score(ytest, ytest_predicted)

'''

'\nSyntaxt for metrics\n\nmetricname(actual_optput, predicted_output)\nr2_score(ytrain, ytrain_predicted)\nr2_score(ytest, ytest_predicted)\n\n'

In [21]:
r2_score(ytrain, ytrain_predicted)

0.9887391160677558

In [22]:
mean_absolute_error(ytrain, ytrain_predicted)

1.6171939645366624

In [23]:
root_mean_squared_error(ytrain, ytrain_predicted)

2.0358228155328564

#### conclusion

MAE and RMSE are almost equal. Hence model captures the pattern properly

#### because of previous score(Highly corelated) column the model give higher accuracy