In [13]:
import pandas as pd
from sklearn.ensemble import IsolationForest

In [14]:
df = pd.read_csv('creditcard.csv')
df.head()

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0

In [15]:
df.shape

(284807, 31)

In [ ]:
model = IsolationForest(n_estimators=100, 
                        max_samples=0.8, 
                        max_features=1.0, 
                        bootstrap=True, 
                        n_jobs=8, 
                        verbose=1,
                        contamination=0.05) # 5% anomaly values to detect

In [17]:
result = model.fit_predict(df)

[Parallel(n_jobs=4)]: Using backend ThreadingBackend with 4 concurrent workers.

Building estimator 1 of 25 for this parallel run (total 100)...Building estimator 1 of 25 for this parallel run (total 100)...

Building estimator 1 of 25 for this parallel run (total 100)...
Building estimator 1 of 25 for this parallel run (total 100)...
Building estimator 2 of 25 for this parallel run (total 100)...
Building estimator 2 of 25 for this parallel run (total 100)...
Building estimator 2 of 25 for this parallel run (total 100)...
Building estimator 2 of 25 for this parallel run (total 100)...
Building estimator 3 of 25 for this parallel run (total 100)...
Building estimator 3 of 25 for this parallel run (total 100)...
Building estimator 3 of 25 for this parallel run (total 100)...
Building estimator 3 of 25 for this parallel run (total 100)...
Building estimator 4 of 25 for this parallel run (total 100)...
Building estimator 4 of 25 for this parallel run (total 100)...
Building estimator 4 of 25 for this parallel run (total 100)...
Building estimator 5 of 25 for this parallel run (total 100)...
Building estimator 4 of 25 for this parallel run (total 100)...
Building estimator 5 of 25 for this parallel run (total 100)...
Building estimator 5 of 25 for this parallel run (total 100)...
Building estimator 5 of 25 for this parallel run (total 100)...
Building estimator 6 of 25 for this parallel run (total 100)...
Building estimator 6 of 25 for this parallel run (total 100)...
Building estimator 6 of 25 for this parallel run (total 100)...
Building estimator 6 of 25 for this parallel run (total 100)...
Building estimator 7 of 25 for this parallel run (total 100)...
Building estimator 7 of 25 for this parallel run (total 100)...
Building estimator 7 of 25 for this parallel run (total 100)...
Building estimator 7 of 25 for this parallel run (total 100)...
Building estimator 8 of 25 for this parallel run (total 100)...
Building estimator 8 of 25 for this parallel run (total 100)...
Building estimator 9 of 25 for this parallel run (total 100)...
Building estimator 8 of 25 for this parallel run (total 100)...
Building estimator 9 of 25 for this parallel run (total 100)...
Building estimator 8 of 25 for this parallel run (total 100)...
Building estimator 10 of 25 for this parallel run (total 100)...
Building estimator 9 of 25 for this parallel run (total 100)...
Building estimator 9 of 25 for this parallel run (total 100)...
Building estimator 10 of 25 for this parallel run (total 100)...
Building estimator 11 of 25 for this parallel run (total 100)...
Building estimator 10 of 25 for this parallel run (total 100)...
Building estimator 11 of 25 for this parallel run (total 100)...
Building estimator 12 of 25 for this parallel run (total 100)...
Building estimator 10 of 25 for this parallel run (total 100)...
Building estimator 11 of 25 for this parallel run (total 100)...
Building estimator 12 of 25 for this parallel run (total 100)...
Building estimator 13 of 25 for this parallel run (total 100)...
Building estimator 11 of 25 for this parallel run (total 100)...
Building estimator 12 of 25 for this parallel run (total 100)...
Building estimator 13 of 25 for this parallel run (total 100)...
Building estimator 14 of 25 for this parallel run (total 100)...
Building estimator 12 of 25 for this parallel run (total 100)...
Building estimator 13 of 25 for this parallel run (total 100)...
Building estimator 14 of 25 for this parallel run (total 100)...
Building estimator 15 of 25 for this parallel run (total 100)...
Building estimator 13 of 25 for this parallel run (total 100)...
Building estimator 14 of 25 for this parallel run (total 100)...
Building estimator 15 of 25 for this parallel run (total 100)...
Building estimator 16 of 25 for this parallel run (total 100)...
Building estimator 14 of 25 for this parallel run (total 100)...
Building estimator 15 of 25 for this parallel run (total 100)...
Building estimator 16 of 25 for this parallel run (total 100)...
Building estimator 17 of 25 for this parallel run (total 100)...
Building estimator 15 of 25 for this parallel run (total 100)...
Building estimator 18 of 25 for this parallel run (total 100)...
Building estimator 16 of 25 for this parallel run (total 100)...
Building estimator 17 of 25 for this parallel run (total 100)...
Building estimator 16 of 25 for this parallel run (total 100)...
Building estimator 17 of 25 for this parallel run (total 100)...
Building estimator 19 of 25 for this parallel run (total 100)...
Building estimator 17 of 25 for this parallel run (total 100)...
Building estimator 18 of 25 for this parallel run (total 100)...
Building estimator 20 of 25 for this parallel run (total 100)...
Building estimator 18 of 25 for this parallel run (total 100)...
Building estimator 19 of 25 for this parallel run (total 100)...
Building estimator 18 of 25 for this parallel run (total 100)...
Building estimator 21 of 25 for this parallel run (total 100)...
Building estimator 19 of 25 for this parallel run (total 100)...
Building estimator 19 of 25 for this parallel run (total 100)...
Building estimator 20 of 25 for this parallel run (total 100)...
Building estimator 22 of 25 for this parallel run (total 100)...
Building estimator 20 of 25 for this parallel run (total 100)...
Building estimator 20 of 25 for this parallel run (total 100)...
Building estimator 23 of 25 for this parallel run (total 100)...
Building estimator 21 of 25 for this parallel run (total 100)...
Building estimator 21 of 25 for this parallel run (total 100)...
Building estimator 21 of 25 for this parallel run (total 100)...
Building estimator 22 of 25 for this parallel run (total 100)...
Building estimator 24 of 25 for this parallel run (total 100)...
Building estimator 22 of 25 for this parallel run (total 100)...
Building estimator 22 of 25 for this parallel run (total 100)...
Building estimator 23 of 25 for this parallel run (total 100)...
Building estimator 25 of 25 for this parallel run (total 100)...
Building estimator 23 of 25 for this parallel run (total 100)...
Building estimator 23 of 25 for this parallel run (total 100)...
Building estimator 24 of 25 for this parallel run (total 100)...
Building estimator 24 of 25 for this parallel run (total 100)...
Building estimator 24 of 25 for this parallel run (total 100)...
Building estimator 25 of 25 for this parallel run (total 100)...
Building estimator 25 of 25 for this parallel run (total 100)...
Building estimator 25 of 25 for this parallel run (total 100)...

[Parallel(n_jobs=4)]: Done   4 out of   4 | elapsed:    2.2s finished
[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:    1.5s
[Parallel(n_jobs=1)]: Done  40 tasks      | elapsed:    1.5s

In [19]:
anomalies = df[result==-1]
normal = df[result==1]

In [20]:
anomalies

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
2,1.0,-1.358354,-1.340163,1.773209,0.379780,-0.503198,1.800499,0.791461,0.247676,-1.514654,...,0.247998,0.771679,0.909412,-0.689281,-0.327642,-0.139097,-0.055353,-0.059752,378.66,0
7,7.0,-0.644269,1.417964,1.074380,-0.492199,0.948934,0.428118,1.120631,-3.807864,0.615375,...,1.943465,-1.015455,0.057504,-0.649709,-0.415267,-0.051634,-1.206921,-1.085339,40.80,0
18,14.0,-5.401258,-5.450148,1.186305,1.736239,3.049106,-1.763406,-1.559738,0.160842,1.233090,...,-0.503600,0.984460,2.458589,0.042119,-0.481631,-0.621272,0.392053,0.949594,46.80,0
51,36.0,-1.004929,-0.985978,-0.038039,3.710061,-6.631951,5.122103,4.371691,-2.006868,-0.278736,...,1.393406,-0.381671,0.969719,0.019445,0.570923,0.333278,0.857373,-0.075538,1402.95,0
69,46.0,-1.923213,-0.870482,2.320170,1.988776,0.417091,-0.380014,0.472139,-0.557333,-0.649079,...,-0.686488,-0.779268,1.086055,0.518863,-0.363712,3.065576,-0.589022,-0.396110,35.00,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284772,172760.0,-6.713826,2.369104,-3.534768,-0.368259,-1.721030,-1.322808,-0.190876,0.891149,2.068476,...,0.131247,0.994246,-0.002140,-0.072979,-0.167159,-0.387271,-2.616341,0.474584,19.59,0
284774,172762.0,-0.725459,0.194981,-1.785571,-3.779860,2.177420,2.975713,-0.239695,0.912303,-3.159994,...,0.046103,0.102480,-0.461027,0.717647,1.253036,0.207138,-0.630549,-0.163911,7.00,0
284795,172778.0,-12.516732,10.187818,-8.476671,-2.510473,-4.586669,-1.394465,-3.632516,5.498583,4.893089,...,-0.944759,-1.565026,0.890675,-1.253276,1.786717,0.320763,2.090712,1.232864,9.87,0
284802,172786.0,-11.881118,10.071785,-9.834783,-2.066656,-5.364473,-2.606837,-4.918215,7.305334,1.914428,...,0.213454,0.111864,1.014480,-0.509348,1.436807,0.250034,0.943651,0.823731,0.77,0
284805,172788.0,-0.240440,0.530483,0.702510,0.689799,-0.377961,0.623708,-0.686180,0.679145,0.392087,...,0.265245,0.800049,-0.163298,0.123205,-0.569159,0.546668,0.108821,0.104533,10.00,0

In [21]:
normal

,Time,V1,V2,V3,V4,V5,V6,V7,V8,V9,...,V21,V22,V23,V24,V25,V26,V27,V28,Amount,Class
0,0.0,-1.359807,-0.072781,2.536347,1.378155,-0.338321,0.462388,0.239599,0.098698,0.363787,...,-0.018307,0.277838,-0.110474,0.066928,0.128539,-0.189115,0.133558,-0.021053,149.62,0
1,0.0,1.191857,0.266151,0.166480,0.448154,0.060018,-0.082361,-0.078803,0.085102,-0.255425,...,-0.225775,-0.638672,0.101288,-0.339846,0.167170,0.125895,-0.008983,0.014724,2.69,0
3,1.0,-0.966272,-0.185226,1.792993,-0.863291,-0.010309,1.247203,0.237609,0.377436,-1.387024,...,-0.108300,0.005274,-0.190321,-1.175575,0.647376,-0.221929,0.062723,0.061458,123.50,0
4,2.0,-1.158233,0.877737,1.548718,0.403034,-0.407193,0.095921,0.592941,-0.270533,0.817739,...,-0.009431,0.798278,-0.137458,0.141267,-0.206010,0.502292,0.219422,0.215153,69.99,0
5,2.0,-0.425966,0.960523,1.141109,-0.168252,0.420987,-0.029728,0.476201,0.260314,-0.568671,...,-0.208254,-0.559825,-0.026398,-0.371427,-0.232794,0.105915,0.253844,0.081080,3.67,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
284800,172784.0,2.039560,-0.175233,-1.196825,0.234580,-0.008713,-0.726571,0.017050,-0.118228,0.435402,...,-0.268048,-0.717211,0.297930,-0.359769,-0.315610,0.201114,-0.080826,-0.075071,2.68,0
284801,172785.0,0.120316,0.931005,-0.546012,-0.745097,1.130314,-0.235973,0.812722,0.115093,-0.204064,...,-0.314205,-0.808520,0.050343,0.102800,-0.435870,0.124079,0.217940,0.068803,2.69,0
284803,172787.0,-0.732789,-0.055080,2.035030,-0.738589,0.868229,1.058415,0.024330,0.294869,0.584800,...,0.214205,0.924384,0.012463,-1.016226,-0.606624,-0.395255,0.068472,-0.053527,24.79,0
284804,172788.0,1.919565,-0.301254,-3.249640,-0.557828,2.630515,3.031260,-0.296827,0.708417,0.432454,...,0.232045,0.578229,-0.037501,0.640134,0.265745,-0.087371,0.004455,-0.026561,67.88,0
284806,172792.0,-0.533413,-0.189733,0.703337,-0.506271,-0.012546,-0.649617,1.577006,-0.414650,0.486180,...,0.261057,0.643078,0.376777,0.008797,-0.473649,-0.818267,-0.002415,0.013649,217.00,0